repos:
  - hooks:
    - additional_dependencies:
      - toml
      id: isort
      stages:
        - commit
    repo: https://github.com/PyCQA/isort
    rev: 5.12.0
  - hooks:
      - id: black
        language_version: python3.8
        stages:
          - commit
    repo: https://github.com/psf/black
    rev: 21.7b0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]